name : Move New User Story to To Do


on: 
  issues:
    types:
      - opened

jobs:
  move_to_todo:
    runs-on: ubuntu-latest
    steps:
      - name: Move to To Do
        run: |
          echo "Moving issue to To Do"
          gh project card create --content-type Issue --column "To Do" --issue "${{ github.even.issue.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
